services:
  openlist:
    build:
      context: .
      network: host
    restart: always
    network_mode: host
    volumes:
      - './data:/opt/openlist/data'
    environment:
      - TZ=Asia/Shanghai
    container_name: openlist
